temp <- tempfile()
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip",temp)
header <- read.table(unz(temp, "household_power_consumption.txt"),sep=";",nrows=1,header=FALSE,stringsAsFactors = FALSE)
data <- read.table(unz(temp, "household_power_consumption.txt"),sep=";",header=TRUE,skip=66636,nrows=2880,quote="",na.strings="?")
unlink(temp)
colnames(data) <- unlist(header)
png("plot1.png", width=480, height=480)
hist(data$Global_active_power,col="red",xlab="Global Active Power (kilowatts)",main="Global Active Power")
dev.off()